# Generated by Django 4.2.26 on 2025-11-15 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('PRANZO', 'Pranzo'), ('CARBURANTE', 'Carburante'), ('TRASPORTO', 'TRASPORTO'), ('VARIE', 'Varie')], max_length=50, verbose_name='Tipologia')),
                ('city', models.CharField(max_length=100, verbose_name='Comune')),
                ('province', models.CharField(max_length=2, verbose_name='Provincia')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Totale spesa')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Data spesa')),
            ],
        ),
        migrations.CreateModel(
            name='ReceiptImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image', models.ImageField(upload_to='receipts/original/', verbose_name='Immagine originale')),
                ('cleaned_image', models.ImageField(blank=True, null=True, upload_to='receipts/cleaned/', verbose_name='Immagine pulita')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='spese_app.expense')),
            ],
        ),
    ]
